### ISSUE TITLE
No metadata are downloaded

### ISSUE THREAD

**Issue by sebbrousse** [dukeboard/basic-maven-resolver#1]
When configuring another directoring, the resolve method does not get the metadata of the jar.

**Comment by dukeboard** [comment]
Good question, currently we only download metadata files in case of snapshot version. 
This metadata file is then used to track updates for next call to the same artifact.
In short currently you will find metadata only for snapshot version, maven repositories follows also quite same behavior. Don't hesitate to let me now if you think to a different behavior :-)

Regards,
